"""Record the explicitly authorized pre-outcome Massive budget amendment."""
import json
from datetime import datetime,timezone
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
path=ROOT/'data/cache/acquisition_budget.json'
ledger=json.loads(path.read_text())
if ledger.get('authority')=='EXPERIMENT.md A7':
    raise SystemExit('A7 already recorded; no duplicate amendment')
now=datetime.now(timezone.utc).isoformat()
with (ROOT/'EXPERIMENT.md').open('a') as f:
    f.write(f'''\n\n### Amendment A7 — full-universe pre-event NBBO acquisition budget\n\nRecorded at: {now}\nAuthorization: Explicit user instruction, justified by the completed representative benchmark, before any X values or strategy outcomes were inspected.\n\nRaise the operational Massive acquisition request ceiling from 2,500 to **20,000 requests**. Preserve the cumulative **4,000,000,000-byte** transfer ceiling. Conservatively count all previously recorded acquisition calls against the 20,000 ceiling in the shared ledger; no provider counter reset or prior request subtraction. Subsequent Databento calls are also recorded against this conservative shared counter unless explicitly separated in a later authorization. This is solely an operational acquisition-budget amendment, with no change to hypotheses, signals, price/liquidity thresholds, universe, split dates, purging, holdout, outcome rules or sample size. The proposed deterministic sample remains inactive; retain all 14,340 operationally eligible development events.\n\nAcquire complete underlying NBBO windows [15:50,15:55) ET using the benchmark implementation: valid SIP timestamps inside the window, positive bid, ask greater than bid, positive sizes, and no nonregular condition codes. Accept absent/empty conditions or code 1 (provider-labelled Regular Two-Sided Open), exactly as in the completed benchmark. Require at least three distinct valid minute bins and define S0 as the median of all valid quote midpoints. Reuse hash-verified complete benchmark windows. Checkpoint each page and complete event; count retries and failed requests/bytes; never use an incomplete page set for S0. Modest concurrency of two independent event windows is operationally permitted under the documented paid-plan request policy, within the existing Slurm compute allocation.\n\nIf S0 coverage is adequate for continued feasibility measurement, proceed directly to historical event-root Databento OPRA.PILLAR definitions, original D+7…D+21 earliest-expiry/nearest-strike/lower-tie/standard-unadjusted-100-share/matching-pair selection, and only selected-pair cbbo-1m in the fixed pre-event window to compute M and contract/quote coverage. The original contract and synchronized-quote thresholds are unchanged. Obtain concrete cost/transfer estimates before billable Databento retrieval, retaining the existing dollar-cost stop until explicitly amended. No post-event/outcome requests, X calculation, subsequent ten-session returns or holdout access are authorized in this acquisition step. Operational FMP timing remains passed with historical timestamp/vintage unproven.\n''')
with (ROOT/'DATA_AUDIT.md').open('a') as f:
    f.write('\n\n## A7 full-universe pre-event NBBO execution\n\nThe latest explicit user authorization raises Massive requests to 20,000 while retaining cumulative 4 GB. Use the shared benchmark validity/window implementation for all 14,340 events, reuse completed benchmark windows and checkpoint pagination. Two concurrent event windows are permitted under paid-plan request policy. Record all calls conservatively in the shared ledger. After adequate S0 coverage, proceed to historical parent definitions and selected-pair-only cbbo-1m for M/coverage, with provider cost checks. No post-event, X, outcomes, subsequent returns or holdout acquisition. EXPERIMENT.md A7 is authoritative.\n')
ledger.update(authority='EXPERIMENT.md A7',request_ceiling=20000,
              remaining_requests=20000-ledger['cumulative_requests'],recorded_at=now)
path.write_text(json.dumps(ledger,indent=2)+'\n')
print(json.dumps(ledger,indent=2))
